"""
LogCentry SIEM - Alert Management

Alert creation, storage, and lifecycle management.
"""

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

from logcentry.utils import get_logger

logger = get_logger(__name__)


class AlertStatus(str, Enum):
    """Alert lifecycle status."""
    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class Alert:
    """
    Security alert generated by detection rules or correlation.
    
    Attributes:
        id: Unique alert identifier
        rule_id: ID of the rule that triggered this alert
        rule_name: Name of the triggering rule
        severity: Alert severity
        status: Current alert status
        project_id: Associated project ID
        source_log_ids: IDs of logs that triggered this alert
        correlation_id: Optional correlation ID if from correlation engine
        mitre_techniques: Associated MITRE ATT&CK techniques
        summary: Brief summary of the alert
        details: Detailed alert information
        created_at: When the alert was created
        updated_at: Last update time
        acknowledged_at: When acknowledged
        acknowledged_by: Who acknowledged
        resolved_at: When resolved
        resolved_by: Who resolved
        resolution_notes: Notes on resolution
    """
    id: str
    rule_id: str
    rule_name: str
    severity: AlertSeverity
    summary: str
    project_id: str | None = None
    status: AlertStatus = AlertStatus.NEW
    source_log_ids: list[str] = field(default_factory=list)
    correlation_id: str | None = None
    mitre_techniques: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)
    entity: str | None = None  # IP or username involved
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    acknowledged_at: datetime | None = None
    acknowledged_by: str | None = None
    resolved_at: datetime | None = None
    resolved_by: str | None = None
    resolution_notes: str | None = None
    
    def acknowledge(self, user: str) -> None:
        """Mark alert as acknowledged."""
        self.status = AlertStatus.ACKNOWLEDGED
        self.acknowledged_at = datetime.utcnow()
        self.acknowledged_by = user
        self.updated_at = datetime.utcnow()
    
    def start_investigation(self) -> None:
        """Mark alert as under investigation."""
        self.status = AlertStatus.IN_PROGRESS
        self.updated_at = datetime.utcnow()
    
    def resolve(self, user: str, notes: str = "") -> None:
        """Mark alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = datetime.utcnow()
        self.resolved_by = user
        self.resolution_notes = notes
        self.updated_at = datetime.utcnow()
    
    def mark_false_positive(self, user: str, notes: str = "") -> None:
        """Mark alert as false positive."""
        self.status = AlertStatus.FALSE_POSITIVE
        self.resolved_at = datetime.utcnow()
        self.resolved_by = user
        self.resolution_notes = notes
        self.updated_at = datetime.utcnow()
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "severity": self.severity.value,
            "status": self.status.value,
            "project_id": self.project_id,
            "source_log_ids": self.source_log_ids,
            "correlation_id": self.correlation_id,
            "mitre_techniques": self.mitre_techniques,
            "summary": self.summary,
            "details": self.details,
            "entity": self.entity,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "acknowledged_by": self.acknowledged_by,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolved_by": self.resolved_by,
            "resolution_notes": self.resolution_notes,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "Alert":
        """Create Alert from dictionary."""
        def parse_dt(s):
            if not s:
                return None
            if isinstance(s, datetime):
                return s
            return datetime.fromisoformat(s)
        
        return cls(
            id=data["id"],
            rule_id=data["rule_id"],
            rule_name=data["rule_name"],
            severity=AlertSeverity(data["severity"]),
            status=AlertStatus(data.get("status", "new")),
            project_id=data.get("project_id"),
            source_log_ids=data.get("source_log_ids", []),
            correlation_id=data.get("correlation_id"),
            mitre_techniques=data.get("mitre_techniques", []),
            summary=data["summary"],
            details=data.get("details", {}),
            entity=data.get("entity"),
            created_at=parse_dt(data.get("created_at")) or datetime.utcnow(),
            updated_at=parse_dt(data.get("updated_at")) or datetime.utcnow(),
            acknowledged_at=parse_dt(data.get("acknowledged_at")),
            acknowledged_by=data.get("acknowledged_by"),
            resolved_at=parse_dt(data.get("resolved_at")),
            resolved_by=data.get("resolved_by"),
            resolution_notes=data.get("resolution_notes"),
        )


class AlertService:
    """
    In-memory alert service for managing alerts.
    
    For production, this would be backed by database.
    """
    
    def __init__(self):
        self._alerts: dict[str, Alert] = {}
        self._project_alerts: dict[str, list[str]] = {}  # project_id -> alert_ids
    
    def create_alert(
        self,
        rule_id: str,
        rule_name: str,
        severity: AlertSeverity | str,
        summary: str,
        project_id: str | None = None,
        source_log_ids: list[str] | None = None,
        correlation_id: str | None = None,
        mitre_techniques: list[str] | None = None,
        details: dict[str, Any] | None = None,
        entity: str | None = None,
    ) -> Alert:
        """
        Create a new alert.
        
        Returns:
            Created Alert object
        """
        if isinstance(severity, str):
            severity = AlertSeverity(severity)
        
        alert = Alert(
            id=str(uuid.uuid4()),
            rule_id=rule_id,
            rule_name=rule_name,
            severity=severity,
            summary=summary,
            project_id=project_id,
            source_log_ids=source_log_ids or [],
            correlation_id=correlation_id,
            mitre_techniques=mitre_techniques or [],
            details=details or {},
            entity=entity,
        )
        
        self._alerts[alert.id] = alert
        
        if project_id:
            if project_id not in self._project_alerts:
                self._project_alerts[project_id] = []
            self._project_alerts[project_id].append(alert.id)
        
        logger.info(
            "alert_created",
            alert_id=alert.id,
            rule_name=rule_name,
            severity=severity.value,
        )
        return alert
    
    def get_alert(self, alert_id: str) -> Alert | None:
        """Get an alert by ID."""
        return self._alerts.get(alert_id)
    
    def get_alerts(
        self,
        project_id: str | None = None,
        status: AlertStatus | str | None = None,
        severity: AlertSeverity | str | None = None,
        limit: int = 100,
    ) -> list[Alert]:
        """
        Get alerts with optional filters.
        
        Args:
            project_id: Filter by project
            status: Filter by status
            severity: Filter by severity
            limit: Maximum number of alerts to return
            
        Returns:
            List of matching alerts
        """
        if isinstance(status, str):
            status = AlertStatus(status)
        if isinstance(severity, str):
            severity = AlertSeverity(severity)
        
        # Get all alerts or filter by project
        if project_id:
            alert_ids = self._project_alerts.get(project_id, [])
            alerts = [self._alerts[aid] for aid in alert_ids if aid in self._alerts]
        else:
            alerts = list(self._alerts.values())
        
        # Apply filters
        if status:
            alerts = [a for a in alerts if a.status == status]
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        
        # Sort by created_at desc
        alerts.sort(key=lambda a: a.created_at, reverse=True)
        
        return alerts[:limit]
    
    def get_active_alerts(self, project_id: str | None = None) -> list[Alert]:
        """Get alerts that are not resolved."""
        alerts = self.get_alerts(project_id=project_id, limit=1000)
        return [a for a in alerts if a.status not in (AlertStatus.RESOLVED, AlertStatus.FALSE_POSITIVE)]
    
    def acknowledge(self, alert_id: str, user: str) -> Alert | None:
        """Acknowledge an alert."""
        alert = self._alerts.get(alert_id)
        if alert:
            alert.acknowledge(user)
            logger.info("alert_acknowledged", alert_id=alert_id, user=user)
        return alert
    
    def resolve(self, alert_id: str, user: str, notes: str = "") -> Alert | None:
        """Resolve an alert."""
        alert = self._alerts.get(alert_id)
        if alert:
            alert.resolve(user, notes)
            logger.info("alert_resolved", alert_id=alert_id, user=user)
        return alert
    
    def mark_false_positive(self, alert_id: str, user: str, notes: str = "") -> Alert | None:
        """Mark an alert as false positive."""
        alert = self._alerts.get(alert_id)
        if alert:
            alert.mark_false_positive(user, notes)
            logger.info("alert_false_positive", alert_id=alert_id, user=user)
        return alert
    
    def get_stats(self, project_id: str | None = None) -> dict:
        """Get alert statistics."""
        alerts = self.get_alerts(project_id=project_id, limit=10000)
        
        by_status = {}
        by_severity = {}
        
        for alert in alerts:
            status = alert.status.value
            severity = alert.severity.value
            
            by_status[status] = by_status.get(status, 0) + 1
            by_severity[severity] = by_severity.get(severity, 0) + 1
        
        active = sum(1 for a in alerts if a.status not in (AlertStatus.RESOLVED, AlertStatus.FALSE_POSITIVE))
        
        return {
            "total": len(alerts),
            "active": active,
            "by_status": by_status,
            "by_severity": by_severity,
        }
    
    def clear(self, project_id: str | None = None) -> int:
        """Clear alerts (for testing)."""
        if project_id:
            alert_ids = self._project_alerts.get(project_id, [])
            for aid in alert_ids:
                if aid in self._alerts:
                    del self._alerts[aid]
            self._project_alerts[project_id] = []
            return len(alert_ids)
        else:
            count = len(self._alerts)
            self._alerts.clear()
            self._project_alerts.clear()
            return count


# Global alert service instance
_alert_service: AlertService | None = None


def get_alert_service() -> AlertService:
    """Get or create the global alert service."""
    global _alert_service
    if _alert_service is None:
        _alert_service = AlertService()
    return _alert_service
